application: social-plusplus

version: 1
runtime: python
api_version: 1
default_expiration: "1d" # expiration time for static content

builtins:
- deferred: on
- appstats: on

includes:
- handlers.yaml
